version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: nodeiq-mosquitto
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./aclfile:/mosquitto/config/aclfile:ro
      - ./certs:/mosquitto/certs:ro
    restart: unless-stopped
