version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./aclfile:/mosquitto/config/aclfile
      - ./certs:/mosquitto/certs
    restart: unless-stopped
